/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../studio/schema.json
export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type BrandReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'brand'
}

export type MaterialReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'material'
}

export type Product = {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  sku?: string
  shortDescription?: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  category?: CategoryReference
  brand?: BrandReference
  materials?: Array<
    {
      _key: string
    } & MaterialReference
  >
  careInstructions?: string
  tags?: Array<string>
  features?: Array<string>
  price?: Price
  variants?: Array<
    {
      _key: string
    } & ProductVariant
  >
  seo?: Seo
}

export type Seo = {
  _type: 'seo'
  metaTitle?: string
  metaDescription?: string
  keywords?: Array<string>
}

export type Price = {
  _type: 'price'
  amount?: number
  compareAtPrice?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Material = {
  _id: string
  _type: 'material'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  composition?: string
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  parent?: CategoryReference
  description?: string
}

export type Size = {
  _id: string
  _type: 'size'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  code?: string
  sortOrder?: number
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Brand = {
  _id: string
  _type: 'brand'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type ColorReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'color'
}

export type SizeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'size'
}

export type ProductVariant = {
  _type: 'productVariant'
  color?: ColorReference
  sizes?: Array<
    {
      _key: string
    } & SizeReference
  >
  sku?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
  available?: boolean
}

export type Color = {
  _id: string
  _type: 'color'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  hexValue?: string
}

export type SanityAgentContext = {
  _id: string
  _type: 'sanity.agentContext'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  groqFilter?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | CategoryReference
  | BrandReference
  | MaterialReference
  | Product
  | Seo
  | Price
  | Slug
  | Material
  | Category
  | Size
  | SanityImageAssetReference
  | Brand
  | SanityImageCrop
  | SanityImageHotspot
  | ColorReference
  | SizeReference
  | ProductVariant
  | Color
  | SanityAgentContext
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: src/sanity/queries/categories.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    description  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: string | null
  description: string | null
}>

// Source: src/sanity/queries/categories.ts
// Variable: CATEGORY_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    description  }
export type CATEGORY_QUERY_RESULT = {
  _id: string
  title: string | null
  slug: string | null
  description: string | null
} | null

// Source: src/sanity/queries/filters.ts
// Variable: FILTER_OPTIONS_QUERY
// Query: {  "categories": *[_type == "category" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current  },  "colors": *[_type == "color" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    hexValue  },  "sizes": *[_type == "size"] | order(sortOrder asc) {    _id,    title,    code,    sortOrder  },  "brands": *[_type == "brand" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current  },  "priceRange": {    "min": math::min(*[_type == "product" && defined(price.amount)].price.amount),    "max": math::max(*[_type == "product" && defined(price.amount)].price.amount)  }}
export type FILTER_OPTIONS_QUERY_RESULT = {
  categories: Array<{
    _id: string
    title: string | null
    slug: string | null
  }>
  colors: Array<{
    _id: string
    title: string | null
    slug: string | null
    hexValue: string | null
  }>
  sizes: Array<{
    _id: string
    title: string | null
    code: string | null
    sortOrder: number | null
  }>
  brands: Array<{
    _id: string
    title: string | null
    slug: string | null
  }>
  priceRange: {
    min: number | null
    max: number | null
  }
}

// Source: src/sanity/queries/products.ts
// Variable: PRODUCTS_QUERY
// Query: *[_type == "product" && defined(slug.current)] | order(_createdAt desc) {      _id,  title,  "slug": slug.current,  shortDescription,  "category": category->{   _id,  title,  "slug": slug.current },  "brand": brand->{   _id,  title,  "slug": slug.current },  "image": variants[0].images[0] {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },  price {   amount,  compareAtPrice }  }
export type PRODUCTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: string | null
  shortDescription: string | null
  category: {
    _id: string
    title: string | null
    slug: string | null
  } | null
  brand: {
    _id: string
    title: string | null
    slug: string | null
  } | null
  image: {
    asset: {
      _id: string
      url: string | null
      metadata: {
        lqip: string | null
        dimensions: SanityImageDimensions | null
      } | null
    } | null
    alt: string | null
  } | null
  price: {
    amount: number | null
    compareAtPrice: number | null
  } | null
}>

// Source: src/sanity/queries/products.ts
// Variable: FEATURED_PRODUCTS_QUERY
// Query: *[_type == "product" && defined(slug.current)] | order(_createdAt desc) [0...8] {      _id,  title,  "slug": slug.current,  shortDescription,  "category": category->{   _id,  title,  "slug": slug.current },  "brand": brand->{   _id,  title,  "slug": slug.current },  "image": variants[0].images[0] {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },  price {   amount,  compareAtPrice }  }
export type FEATURED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: string | null
  shortDescription: string | null
  category: {
    _id: string
    title: string | null
    slug: string | null
  } | null
  brand: {
    _id: string
    title: string | null
    slug: string | null
  } | null
  image: {
    asset: {
      _id: string
      url: string | null
      metadata: {
        lqip: string | null
        dimensions: SanityImageDimensions | null
      } | null
    } | null
    alt: string | null
  } | null
  price: {
    amount: number | null
    compareAtPrice: number | null
  } | null
}>

// Source: src/sanity/queries/products.ts
// Variable: PRODUCT_QUERY
// Query: *[_type == "product" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    sku,    shortDescription,    description,    features,    careInstructions,    "category": category->{   _id,  title,  "slug": slug.current },    "brand": brand->{   _id,  title,  "slug": slug.current },    price {   amount,  compareAtPrice },    "materials": materials[]->{ _id, title },    "variants": variants[] {   _key,  sku,  available,  "color": color->{ _id, title, hex },  "sizes": sizes[]->{ _id, title, code, sortOrder },  "images": images[] {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt } }  }
export type PRODUCT_QUERY_RESULT = {
  _id: string
  title: string | null
  slug: string | null
  sku: string | null
  shortDescription: string | null
  description: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  features: Array<string> | null
  careInstructions: string | null
  category: {
    _id: string
    title: string | null
    slug: string | null
  } | null
  brand: {
    _id: string
    title: string | null
    slug: string | null
  } | null
  price: {
    amount: number | null
    compareAtPrice: number | null
  } | null
  materials: Array<{
    _id: string
    title: string | null
  }> | null
  variants: Array<{
    _key: string
    sku: string | null
    available: boolean | null
    color: {
      _id: string
      title: string | null
      hex: null
    } | null
    sizes: Array<{
      _id: string
      title: string | null
      code: string | null
      sortOrder: number | null
    }> | null
    images: Array<{
      asset: {
        _id: string
        url: string | null
        metadata: {
          lqip: string | null
          dimensions: SanityImageDimensions | null
        } | null
      } | null
      alt: string | null
    }> | null
  }> | null
} | null

// Source: src/sanity/queries/products.ts
// Variable: PRODUCT_SLUGS_QUERY
// Query: *[_type == "product" && defined(slug.current)] {    "slug": slug.current  }
export type PRODUCT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null
}>

// Source: src/sanity/queries/products.ts
// Variable: PRODUCTS_COUNT_QUERY
// Query: count(*[_type == "product" && defined(slug.current)])
export type PRODUCTS_COUNT_QUERY_RESULT = number

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "category" && defined(slug.current)] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description\n  }\n': CATEGORIES_QUERY_RESULT
    '\n  *[_type == "category" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    description\n  }\n': CATEGORY_QUERY_RESULT
    '{\n  "categories": *[_type == "category" && defined(slug.current)] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current\n  },\n  "colors": *[_type == "color" && defined(slug.current)] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    hexValue\n  },\n  "sizes": *[_type == "size"] | order(sortOrder asc) {\n    _id,\n    title,\n    code,\n    sortOrder\n  },\n  "brands": *[_type == "brand" && defined(slug.current)] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current\n  },\n  "priceRange": {\n    "min": math::min(*[_type == "product" && defined(price.amount)].price.amount),\n    "max": math::max(*[_type == "product" && defined(price.amount)].price.amount)\n  }\n}': FILTER_OPTIONS_QUERY_RESULT
    '\n  *[_type == "product" && defined(slug.current)] | order(_createdAt desc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  shortDescription,\n  "category": category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "brand": brand->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "image": variants[0].images[0] { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n  price { \n  amount,\n  compareAtPrice\n }\n\n  }\n': PRODUCTS_QUERY_RESULT
    '\n  *[_type == "product" && defined(slug.current)] | order(_createdAt desc) [0...8] {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  shortDescription,\n  "category": category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "brand": brand->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "image": variants[0].images[0] { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n  price { \n  amount,\n  compareAtPrice\n }\n\n  }\n': FEATURED_PRODUCTS_QUERY_RESULT
    '\n  *[_type == "product" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    sku,\n    shortDescription,\n    description,\n    features,\n    careInstructions,\n    "category": category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n    "brand": brand->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n    price { \n  amount,\n  compareAtPrice\n },\n    "materials": materials[]->{ _id, title },\n    "variants": variants[] { \n  _key,\n  sku,\n  available,\n  "color": color->{ _id, title, hex },\n  "sizes": sizes[]->{ _id, title, code, sortOrder },\n  "images": images[] { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n }\n }\n  }\n': PRODUCT_QUERY_RESULT
    '\n  *[_type == "product" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': PRODUCT_SLUGS_QUERY_RESULT
    '\n  count(*[_type == "product" && defined(slug.current)])\n': PRODUCTS_COUNT_QUERY_RESULT
  }
}
